name: verify_user_in_organization
description: Verify user in organization
inputs:
  username:
    description: "The id of the user"
    required: true
  token:
    description: "Token to access Github API"
    required: true
runs:
  using: composite
  steps:
    - name: Verify user in organization
      id: verify_user_in_organization
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        USERNAME: ${{ inputs.username }}
      run: |
        echo "Verifying user's organization..."
        response=$(curl -s -L \
            -w "%{http_code}" \
            -o /dev/null -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/orgs/deriv-com/memberships/$USERNAME")
            
        if [ $response != "200" ]; then
            echo "User is not a member of deriv-com organization."
            exit 1
        else
            echo "User is a member of deriv-com organization."
        fi
