name: post_preview_link_comment
description: Post preview link comment
inputs:
  issue_number:
    description: "PR number"
    required: true
  preview_url:
    description: "URL of the published deployment"
    required: true
  check_run_id:
    description: "Id of the created check"
    required: true
  status:
    description: "Status of the job"
    required: true
runs:
  using: composite
  steps:
    - name: "Post preview link comment"
      if: ${{ inputs.status == 'success' }}
      id: post_preview_comment
      uses: actions/github-script@v3
      env:
        PREVIEW_URL: ${{ inputs.preview_url }}
      with:
        github-token: ${{ github.token }}
        script: |
          const action_url = "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
          const preview_url = process.env.PREVIEW_URL
          const comment = [
              `**Preview Link**: ${preview_url}`,
              '| Name | Result |',
              '| :--- | :------ |',
              `| **Build status**  | Completed ✅ |`,
              `| **Preview URL**  | [Visit Preview](${preview_url}) |`,
              `| **Action URL**  | [Visit Action](${action_url}) |`,
              ''
            ].join('\n')
          core.setOutput("comment", comment);
    - name: "Post failure comment"
      if: ${{ inputs.status == 'failure' }}
      id: post_failure_comment
      uses: actions/github-script@v3
      with:
        github-token: ${{ github.token }}
        script: |
          const action_url = "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
          const comment = [
            '| Name | Result |',
            '| :--- | :------ |',
            `| **Build status**  | Failed ❌ |`,
            `| **Action URL**  | [Visit Action](${action_url}) |`,
            ''
          ].join('\n')
          core.setOutput("comment", comment);
    - name: Post Cloudflare Pages Preview comment
      if: ${{ inputs.status == 'success' || inputs.status == 'failure' }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: Cloudflare Pages Preview Comment
        number: ${{ inputs.issue_number }}
        message: ${{steps.post_preview_comment.outputs.comment || steps.post_failure_comment.outputs.comment }}
        recreate: true

    - name: "Update the build check"
      uses: actions/github-script@v7
      if: always()
      env:
        CHECK_RUN_ID: ${{ inputs.check_run_id }}
        STATUS: ${{ inputs.status }}
      with:
        github-token: ${{ github.token }}
        script: |
          const conclusion = process.env.STATUS
          const action_url = "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
          await github.rest.checks.update({
            ...context.repo,
            name: "Generate preview link",
            check_run_id: process.env.CHECK_RUN_ID,
            details_url: action_url,
            status: "completed",
            conclusion,
            output: {
              title: "Generate preview link",
              summary: `Preview link creation status: ${conclusion}. Build URL: - ${action_url}`,
            },
          });
