name: Claude Code Review Assistant
description: Review pull requests using Claude AI with organization member verification

inputs:
  github_token:
    description: "GitHub token for PR operations"
    required: true
  anthropic_api_key:
    description: "Anthropic API key for Claude"
    required: true
  pr_number:
    description: "Pull request number"
    required: true
  pr_head_repo:
    description: "Pull request head repository full name"
    required: true
  pr_head_ref:
    description: "Pull request head ref"
    required: true
  repository:
    description: "Repository name (owner/repo)"
    required: true
  review_prompt:
    description: "Custom review prompt (optional)"
    required: false
    default: |
      Please review this pull request with a focus on:
      - Correctness, regressions, and edge cases
      - Code quality & readability (React + TypeScript best practices)
      - Performance (render cost, memoization, effects)
      - Security (XSS, auth flows, secrets)
      - Tests (coverage for new logic)

      Output:
      - Inline comments for specific issues
      - A summary comment with high/medium/low priority items
      - Concrete fix suggestions and quick patches where safe

runs:
  using: composite
  steps:
    # Ensure we have a real git repo at the PR HEAD (works for forks)
    - name: Checkout PR head
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.pr_head_repo }}
        ref: ${{ inputs.pr_head_ref }}
        fetch-depth: 20
        token: ${{ inputs.github_token }}

    # Sanity check (helps diagnose if anything goes wrong)
    - name: Verify git workspace
      shell: bash
      run: |
        pwd
        git rev-parse --is-inside-work-tree
        git log -1 --oneline

    - name: Run Claude Code Action
      uses: anthropics/claude-code-action@v1
      with:
        github_token: ${{ inputs.github_token }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        track_progress: true
        prompt: |
          REPO: ${{ inputs.repository }}
          PR NUMBER: ${{ inputs.pr_number }}

          ${{ inputs.review_prompt }}
